src/Entity/Book.php
<?php

namespace App\Entity;

use App\Repository\BookRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=BookRepository::class)
 */
class Book
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToMany(targetEntity=Author::class, inversedBy="books")
     */
    private $Author;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Title;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $Price;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $Quantity;


    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    /**
     * @ORM\ManyToMany(targetEntity=Order::class, mappedBy="Name")
     */
    private $orders;

    /**
     * @ORM\ManyToMany(targetEntity=Type::class, mappedBy="Title")
     */
    private $types;

    public function __construct()
    {
        $this->Author = new ArrayCollection();
        $this->orders = new ArrayCollection();
        $this->types = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Author[]
     */
    public function getAuthor(): Collection
    {
        return $this->Author;
    }

    public function addAuthor(Author $author): self
    {
        if (!$this->Author->contains($author)) {
            $this->Author[] = $author;
        }

        return $this;
    }

    public function removeAuthor(Author $author): self
    {
        $this->Author->removeElement($author);

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->Title;
    }

    public function setTitle(string $Title): self
    {
        $this->Title = $Title;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->Price;
    }

    public function setPrice(?float $Price): self
    {
        $this->Price = $Price;

        return $this;
    }

    public function getQuantity(): ?int
    {
        return $this->Quantity;
    }

    public function setQuantity(?int $Quantity): self
    {
        $this->Quantity = $Quantity;

        return $this;
    }


    public function getImage()
    {
        return $this->Image;
    }

    public function setImage($Image)
    {
        $this->Image = $Image;

        return $this;
    }

    /**
     * @return Collection|Order[]
     */
    public function getOrders(): Collection
    {
        return $this->orders;
    }

    public function addOrder(Order $order): self
    {
        if (!$this->orders->contains($order)) {
            $this->orders[] = $order;
            $order->addName($this);
        }

        return $this;
    }

    public function removeOrder(Order $order): self
    {
        if ($this->orders->removeElement($order)) {
            $order->removeName($this);
        }

        return $this;
    }

    /**
     * @return Collection|Type[]
     */
    public function getTypes(): Collection
    {
        return $this->types;
    }

    public function addType(Type $type): self
    {
        if (!$this->types->contains($type)) {
            $this->types[] = $type;
            $type->addTitle($this);
        }

        return $this;
    }

    public function removeType(Type $type): self
    {
        if ($this->types->removeElement($type)) {
            $type->removeTitle($this);
        }

        return $this;
    }
}

src/Entity/Type.php
<?php

namespace App\Entity;

use App\Repository\TypeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=TypeRepository::class)
 */
class Type
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id; 

    /**
     * @ORM\ManyToMany(targetEntity=Book::class, inversedBy="types")
     */
    private $Title;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Name;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $Image;

    public function __construct()
    {
        $this->Title = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection|Book[]
     */
    public function getTitle(): Collection
    {
        return $this->Title;
    }

    public function addTitle(Book $title): self
    {
        if (!$this->Title->contains($title)) {
            $this->Title[] = $title;
        }

        return $this;
    }

    public function removeTitle(Book $title): self
    {
        $this->Title->removeElement($title);

        return $this;
    }

    public function getName(): ?string
    {
        return $this->Name;
    }

    public function setName(?string $Name): self
    {
        $this->Name = $Name;

        return $this;
    }

    public function getImage()
    {
        return $this->Image;
    }

    public function setImage($Image)
    {
        if ($Image != null) {
            $this->Image = $Image;
        }
        $this->Image = $Image;

        return $this;
    }
}

src/Form/BookType.php
<?php

namespace App\Form;

use App\Entity\Author;
use App\Entity\Book;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class BookType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Title', TextType::class,['required' => true])
            ->add('Price' , MoneyType::class,['currency' => "USD"])
            ->add('Quantity', IntegerType::class,['required' => true])
            ->add('Author', EntityType::class,[
                'class' => Author::class,
                'choice_label' => 'name',
                'multiple' => true,  
                'expanded' => false 
            ])
            -> add('Image', FileType::class,
            [
                'data_class' => null,
                'required' => is_null($builder->getData()->getImage())
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Book::class,
        ]);
    }
}

src/Controller/BookController.php
<?php

namespace App\Controller;

use App\Entity\Book;
use App\Form\BookType;
use App\Repository\AuthorRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Serializer\SerializerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\File\Exception\FileException;

use function PHPUnit\Framework\throwException;

class BookController extends AbstractController
{
    /**
     * @Route("/book", name="book_list")
     */
    public function listBook() 
    {
        $books = $this->getDoctrine()->getRepository(Book::class)->findAll();
        return $this->render('book/index.html.twig', ['books' => $books,]);
    }

    /**
     * @Route("/bookuser", name="book_list_user")
     */
    public function listBookUser() 
    {
        $books = $this->getDoctrine()->getRepository(Book::class)->findAll();
        return $this->render('user/index.html.twig', ['books' => $books,]);
    }

    /**
     * @Route("/book/detail/{id}", name="book_detail")
     */
    public function detailBook($id) 
    {
        $book = $this->getDoctrine()->getRepository(Book::class)->find($id);
        return $this->render('book/detail.html.twig', ['book' => $book,]);
    }

    /**
     * @Route("/bookuser/detail/{id}", name="book_detail_user")
     */
    public function detailBookUser($id) 
    {
        $book = $this->getDoctrine()->getRepository(Book::class)->find($id);
        return $this->render('user/detail.html.twig', ['book' => $book,]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/book/delete/{id}", name="book_delete")
     */
    public function deleteBook($id) {
        $book = $this->getDoctrine()->getRepository(Book::class)->find($id);
        if ($book == null) {
            $this->addFlash("Error","Invalid book ID");
            return $this->redirectToRoute("book_list");
        }
        $manager = $this->getDoctrine()->getManager();
        $manager->remove($book);
        $manager->flush();
        $this->addFlash("Success","Delete book succeed !");
        return $this->redirectToRoute('book_list');
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/book/create", name="book_create")
     */
    public function createBook(Request $request) {
        $book = new Book();
        $form = $this->createForm(BookType::class,$book);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $image = $book->getImage();
            $fileName = md5(uniqid());
            $fileExtension = $image->guessExtension();
            $imageName = $fileName . '.' . $fileExtension;
            try {
                $image->move($this->getParameter('book_image'), $imageName);
            } catch (FileException $e) {
                throwException($e);
            }
            $book->setImage($imageName);
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($book);
            $manager->flush();
            $this->addFlash("Success","Create book successfully !");
            return $this->redirectToRoute("book_list");
        }
        return $this->render("book/create.html.twig",["form" => $form->createView()]);
    }

    /**
     * @IsGranted("ROLE_ADMIN")
     * @Route("/book/update/{id}", name="book_update")
     */
    public function updateBook(Request $request, $id) {
        $book = $this->getDoctrine()->getRepository(Book::class)->find($id);
        $form = $this->createForm(BookType::class,$book);
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $image = $book->getImage();
            $fileName = md5(uniqid());
            $fileExtension = $image->guessExtension();
            $imageName = $fileName . '.' . $fileExtension;
            try {
                $image->move($this->getParameter('book_image'), $imageName);
            } catch (FileException $e) {
                throwException($e);
            }
            $book->setImage($imageName);
            $manager = $this->getDoctrine()->getManager();
            $manager->persist($book);
            $manager->flush();
            $this->addFlash("Success","Update book successfully !");
            return $this->redirectToRoute("book_list");
        }
        return $this->render("book/update.html.twig",["form" => $form->createView()]);
    }
}

templates/book/create.html.twig
{% extends "base.html.twig" %}

{% block title %} Create book {% endblock %}

{% block body %}
  <div class="container-fluid mt-3">
      <h2 class="text-center mt-5">CREATE BOOK</h2>
      <div class="col-md-6"></div>
          {{ form_start (form) }}
              <div class="form-group">
                  <p class="text-info text-bold"> Book Title </p>                  
                  {{ form_widget (form.Title, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group">
                  <p class="text-info text-bold"> Book Price </p>                  
                  {{ form_widget (form.Price, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group">
                  <p class="text-info text-bold"> Book Quantity </p>                  
                  {{ form_widget (form.Quantity, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group">
                  <p class="text-info text-bold"> Publisher </p>                  
                  {{ form_widget (form.Author, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group">
                  <p class="text-info text-bold"> Book Image </p>
                  {{ form_widget (form.Image, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group text-center mt-3">
                  <button class="btn btn-primary btn-lg">CREATE</button>
              </div>
          {{ form_end (form)}}
  </div>   
{% endblock %}

templates/book/detail.html.twig
{% extends 'base.html.twig' %}

{% block title %} Book Detail {% endblock %}

{% block body %}

<div class="container-fluid">
<a class="btn btn-primary" href="{{ path ('book_list') }}">Book List</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Book Title</th>
            <th scope="col">Book Price</th>
            <th scope="col">Book Quantity</th>
            <th scope="col">Book Image</th>
            <th scope="col">Book Authors</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td scope="row">{{ book.title }}</td>
            <td scope="row">{{ book.price }}</td>
            <td scope="row">{{ book.quantity }}</td>
            <td scope="row">
                {% for a in book.author %}
                  <a href="{{ path('author_detail', {'id' : a.id }) }}">
                       {{ a.name }}
                  </a>
                  <br>
                {% endfor %}
            </td>
            <td scope="row">
                    <img src="{{asset('images/book/' ~ book.image)}}" width="200px" height="288px"/>
            </td>
            <td scope="row"> 
                <a class="btn btn-warning" href="{{ path ( 'book_update' , {'id' : book.id } ) }}">Update</a>
                <a class="btn btn-danger" href="{{ path ( 'book_delete' , {'id' : book.id } ) }}"
                                          onclick = "return confirm('Are you sure to delete ?')"
                >Delete</a>
            </td>
        </tr> 
    </tbody>
</table>
</div>
{% endblock %}

templates/book/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Book List{% endblock %}
{% block body %}
<div class="container mt-3">
    {% for flash in app.flashes("Success") %}
        <p class="alert alert-primary"> {{ flash }} </p>
    {% endfor %}
    {% for flash in app.flashes("Error") %}
        <p class="alert alert-danger"> {{ flash }} </p>
    {% endfor %}
</div>
<a class="btn btn-primary" href="{{path('book_create')}}">Create</a>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Book ID</th>
            <th scope="col">Book Title</th>
            <th scope="col">Book Image</th>
            <th scope="col">Actions</th>
        </tr>
    </thead>
    <tbody>
    {% for book in books %}
        <tr>
            <td scope="row">{{book.id}}</td>
            <td scope="row">{{book.title}}</td>
            <td scope="row">
                    <img src="{{asset('images/book/' ~ book.image)}}" width="200px" height="288px"/>
            </td>
            <td scope="row">
                <a class="btn btn-info" href="{{path('book_detail', {'id':book.id})}}">View detail</a>
                <a class="btn btn-warning" href="{{path('book_update', {'id':book.id})}}">Update</a>
                <a class="btn btn-danger" href="{{path('book_delete', {'id':book.id})}}"
                onclick="return confirm('Are you sure to delete ?')"
                >Delete</a>
            </td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

templates/book/update.html.twig
{% extends "base.html.twig" %}

{% block title %} Update book {% endblock %}

{% block body %}
  <div class="container-fluid mt-3">
      <h2 class="text-center mt-5">UPDATE BOOK</h2>
      <div class="col-md-6"></div>
          {{ form_start (form) }}
              <div class="form-group">
                  <p class="text-info text-bold"> Book Title </p>
                  {{ form_widget (form.Title, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group">
                <p class="text-info text-bold"> Book Price </p>                  
                {{ form_widget (form.Price, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group">
                <p class="text-info text-bold"> Book Quantity </p>                  
                {{ form_widget (form.Quantity, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group">
                <p class="text-info text-bold"> Book's Author </p>                  
                  {{ form_widget (form.Author, {'attr': {'class' : 'form-control'}}) }}
              </div>
              <div class="form-group">
                    <p class="text-info text-bold"> Book Image </p>
                    {{ form_widget (form.Image, {'attr': {'class' : 'form-control'}}) }}
                </div>
              <div class="form-group text-center mt-3">
                  <button class="btn btn-primary btn-lg">UPDATE</button>
              </div>
          {{ form_end (form)}}
  </div>   
{% endblock %}